#!/bin/bash

set -e -o pipefail

microdnf repolist
if [[ -n "${YUM_ALL_REPOS}" ]] ; then
	microdnf --setopt=tsflags=nodocs install --assumeyes epel-release

	grep -E "^\[" /etc/yum.repos.d/*.repo | tr --delete '[]' | xargs yum-config-manager --enable
fi

microdnf --setopt=tsflags=nodocs install --assumeyes "$@"
