#!/bin/bash

set -e

microdnf repolist
if [[ -n "$YUM_ALL_REPOS" ]] ; then
	microdnf --setopt=tsflags=nodocs install --assumeyes epel-release

	egrep "^\[" /etc/yum.repos.d/*.repo | tr --delete '[]' | xargs yum-config-manager --enable
fi

microdnf --setopt=tsflags=nodocs install --assumeyes $@
