#!/bin/bash

set -e

source /usr/local/lib/entrypoint.sh

secrets=$EP_SECRETS_ROOT/ejbca_keystore_password
if [[ -e $secrets ]] ; then
	generate_password ejbca_keystore
else
	read -p "ejbca keystore password not found, please provide:" -s EJBCA_KEYSTORE_PASSWORD
	echo ""
fi

if [[ -z $EJBCA_KEYSTORE_PASSWORD ]] ; then
	echo "Unable to retrieve ejbca keystore password!"
	exit 1
fi

su --command="cd $EJBCA_DATA && $EJBCA_HOME/bin/ejbca.sh ra setendentitystatus tomcat 10" --login jboss
su --command="cd $EJBCA_DATA && $EJBCA_HOME/bin/ejbca.sh ra setclearpwd tomcat $EJBCA_KEYSTORE_PASSWORD" --login jboss
su --command="cd $EJBCA_DATA && $EJBCA_HOME/bin/ejbca.sh batch tomcat" --login jboss

cp $EJBCA_DATA/p12/tomcat.jks $JBOSS_HOME/standalone/configuration/keystore/keystore.jks
ls -l $EJBCA_DATA/p12/tomcat.jks $JBOSS_HOME/standalone/configuration/keystore/keystore.jks

echo "*** JBoss must be restared to apply the changes! ***"

