#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh

secrets="${EP_SECRETS_ROOT}/ejbca_keystore_password"
if [[ ! -e "${secrets}" ]] ; then
	generate_password ejbca_keystore
else
	read -p "ejbca keystore password not found, please provide:" -r -s EJBCA_KEYSTORE_PASSWORD
	echo ""
fi

if [[ -z "${EJBCA_KEYSTORE_PASSWORD}" ]] ; then
	echo "Unable to retrieve ejbca keystore password!"
	exit 1
fi

su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setendentitystatus tomcat 10" --login ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setclearpwd tomcat \"${EJBCA_KEYSTORE_PASSWORD}\"" --login ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" batch tomcat" --login ejbca

keystore="${EJBCA_DATA}/p12/tomcat.jks"

# Deploy to running instance (doesn't always work) ...
install --group root --mode 0644 --owner ejbca "${keystore}" "${JBOSS_HOME}/standalone/configuration/keystore.jks"

# Deploy to location that /opt/primekey/bin/internal/after-deployed.sh uses ...
install --group root --mode 0644 --owner ejbca "${keystore}" "/opt/primekey/secrets/persistent/tls/$(hostname)/server.jks"
install --group root --mode 0640 --owner ejbca /dev/null "/opt/primekey/secrets/persistent/tls/$(hostname)/server.storepasswd"
echo "${EJBCA_KEYSTORE_PASSWORD}" > "/opt/primekey/secrets/persistent/tls/$(hostname)/server.storepasswd"

ls -l "${keystore}" "${JBOSS_HOME}/standalone/configuration/keystore.jks" "/opt/primekey/secrets/persistent/tls/$(hostname)/server."*

echo "*** JBoss must be restared to apply the changes! ***"

