#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh

secrets="${EP_SECRETS_ROOT}/ejbca_truststore_password"
if [[ ! -e "${secrets}" ]] ; then
	generate_password ejbca_truststore
else
	read -p "ejbca truststore password not found, please provide:" -r -s EJBCA_TRUSTSTORE_PASSWORD
	echo ""
fi

EJBCA_CA_NAME="${1}"
if [[ -z "${EJBCA_CA_NAME}" ]] ; then
	read -p "What is the name of the CA?: " -r EJBCA_CA_NAME
fi

if [[ -z "${EJBCA_TRUSTSTORE_PASSWORD}" ]] ; then
	echo "Unable to retrieve ejbca truststore password!"
	exit 1
fi

tmp="$(mktemp --dry-run)"
truststore="${EJBCA_DATA}/p12/truststore.jks"
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ca getcacert --caname=\"${EJBCA_CA_NAME}\" -f \"${tmp}\"" --login ejbca
rm "${truststore}"
keytool -importcert -noprompt -alias trusted-ca -file "${tmp}" -keystore "${truststore}" -storepass "${EJBCA_TRUSTSTORE_PASSWORD}"
rm "${tmp}"

chown jboss:jboss "${truststore}"
install --group root --mode 0644 --owner ejbca "${truststore}" "${JBOSS_HOME}/standalone/configuration/truststore.jks"
ls -l "${truststore}" "${JBOSS_HOME}/standalone/configuration/truststore.jks"

echo "*** JBoss must be restared to apply the changes! ***"

