#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh

secrets="${EP_SECRETS_ROOT}/ejbca_admin_password"
if [[ -e "${secrets}" ]] ; then
	generate_password ejbca_admin
else
	read -p "EJBCA admin password not found, please provide:" -r -s EJBCA_ADMIN_PASSWORD
	echo ""
fi

if [[ -z "${EJBCA_ADMIN_PASSWORD}" ]] ; then
	echo "Unable to retrieve ejbca admin password!"
	exit 1
fi

superadmin="${EJBCA_DATA}/p12/superadmin.p12"
[[ -e "${superadmin}" ]] && mv "${superadmin}" "${superadmin}.old"

su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setendentitystatus superadmin 10" ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setclearpwd superadmin \"${EJBCA_ADMIN_PASSWORD}\"" ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" batch" ejbca
chmod 0644 "${superadmin}"
chown ejbca:root "${superadmin}"

ls -l "${superadmin}"
keytool -list -keystore "${superadmin}" -storepass "${EJBCA_ADMIN_PASSWORD}" -storetype JKS

