#!/bin/bash

set -e -o pipefail

source /usr/local/lib/entrypoint.sh

secrets="${EP_SECRETS_ROOT}/ejbca_keystore_password"
if [[ -e "${secrets}" ]] ; then
	generate_password ejbca_keystore
else
	read -p "EJBCA keystore password not found, please provide:" -r -s EJBCA_KEYSTORE_PASSWORD
	echo ""
fi

if [[ -z "${EJBCA_KEYSTORE_PASSWORD}" ]] ; then
	echo "Unable to retrieve ejbca keystore password!"
	exit 1
fi

keystore="${EJBCA_DATA}/p12/server.jks"
[[ -e "${keystore}" ]] && mv "${keystore}" "${keystore}.old"

name="$(hostname)"
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setendentitystatus ${name} 10" ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" ra setclearpwd ${name} \"${EJBCA_KEYSTORE_PASSWORD}\"" ejbca
su --command="cd \"${EJBCA_DATA}\" && \"${EJBCA_HOME}/bin/ejbca.sh\" batch ${name}" ejbca
mv "${EJBCA_DATA}/p12/${name}.jks" "${keystore}"
chmod 0644 "${keystore}"
chown ejbca:root "${keystore}"

# Deploy to running instance (doesn't always work) ...
install --group root --mode 0644 --owner ejbca "${keystore}" "${JBOSS_HOME}/standalone/configuration/keystore.jks"

# Deploy to location that /opt/keyfactor/bin/internal/after-deployed.sh uses ...
install --group root --mode 0644 --owner ejbca "${keystore}" "${EJBCA_DATA}/secrets/tls/ks/server.jks"
install --group root --mode 0640 --owner ejbca /dev/null "${EJBCA_DATA}/secrets/tls/ks/server.storepasswd"
echo "${EJBCA_KEYSTORE_PASSWORD}" > "${EJBCA_DATA}/secrets/tls/ks/server.storepasswd"

ls -l "${keystore}" "${JBOSS_HOME}/standalone/configuration/keystore.jks" "${EJBCA_DATA}/secrets/tls/ks/server."*
keytool -list -keystore "${keystore}" -storepass "${EJBCA_KEYSTORE_PASSWORD}" -storetype JKS

echo "*** JBoss must be restared to apply the changes! ***"

