#!/usr/bin/make -f

image=ejbca
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

dbtag=202002231645

runargs=--publish-all \
	--env=DATABASE_JDBC_URL="jdbc:mysql://ejbca-db:3306/ejbca?characterEncoding=UTF-8" \
	--env=DATABASE_PASSWORD=p4ssword

dbrunargs=--env=MYSQL_DATABASE=ejbca \
	--env=MYSQL_USER=ejbca \
	--env=MYSQL_USER_PASSWORD=p4ssword
