#!/usr/bin/make -f

image=ejbca
tag=SNAPSHOT
name=$(image)-$(tag)
registry=crashvb

runargs=--publish-all \
	--env=EJBCA_DATABASE_PASSWORD=p4ssword \
	--env=EJBCA_DATASOURCE=mysql

dbrunargs=--env=MYSQL_DATABASE=ejbca \
	--env=MYSQL_USER=ejbca \
	--env=MYSQL_USER_PASSWORD=p4ssword
