#!/usr/bin/make -f

image=ejbca
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

dbtag=202002231645

runargs=--publish-all \
	--env=DATABASE_JDBC_URL="jdbc:mysql://ejbca-db:3306/ejbca?characterEncoding=UTF-8" \
	--env=DATABASE_PASSWORD=p4ssword

dbrunargs=--env=MYSQL_DATABASE=ejbca \
	--env=MYSQL_USER=ejbca \
	--env=MYSQL_USER_PASSWORD=p4ssword
